dep 'ssh' do
  requires [
    'openssh-server.bin',
    'secure-opensshd',
    'ssh.authorized-keys'
  ]
  
  before {
    '/etc/ssh/sshd_config'.p.copy('/etc/ssh/sshd_config.backup')
  }
end

dep 'openssh-server.bin' do
  provides 'sshd'
end

dep 'secure-opensshd' do
  requires [
    'secure-sshd-password-authentication',
    'secure-sshd-port'
  ]

  after { 
    shell 'service ssh restart' 
  }  
end

dep 'secure-sshd-password-authentication' do
  met? {
    !'/etc/ssh/sshd_config'.p.read.match(/#PasswordAuthentication yes/)
  }
  
  meet {
    shell "sed -i -e 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config"    
  }
end

dep 'secure-sshd-port' do
  met? {
    !'/etc/ssh/sshd_config'.p.read.match(/Port 22/)
  }
  
  meet {
    shell "sed -i -e 's/^Port 22/Port 23222/' /etc/ssh/sshd_config"
  }
end

dep 'ssh.authorized-keys' do
  met? {
    if "/root/.ssh/authorized_keys".p.grep(/# generated by Babushka/)
      true
    else
      false
    end
  }
  
  meet {
    '/root/.ssh/authorized_keys'.p.append("# generated by Babushka\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzozCvmikj7094V99QonFrDMMGHWVqmpE6rXGq/DP7DTqyGxWQHiebS5iEKDNmnsBEbDSomV62ckXVwQQYh9dCXUOEOdk5fFeEel+jiqqllYkigb4lwlNiG7tmpH7xdewJ3w4qKowrLuuD6Voa1s4k4TsLp1G1YpQVFPdDfoyUjNCozKciW4DD4YXO4yIz8lfsAK6rVg63+Gbl8wTEQeLFzTtqBEpxXHWuadI8d1clUM2b/pNkK99MjIVLwCzUxSbtao1Lj0faRYjLpvBWu5GY6to6VIEV69s4+1pNe49hXuGxe0zUTxvjxWfQJRSIMRYrSXCtLXKOWuiJM1X/QucKQ== sebastiandeutsch\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Cet5vK+acVgrNSVrJJpaCMhlyUBwKDjpKDT9GVLp3J10Hizu0f/iEqaIJJRVZLslrMHFMOsZzssowFl17VQzTwocd/qAUP8g3y3dLP9XD6oJNmB7z/ABvgoYv0GRV5mzLurf8f6pThbopyIuMgSzHgkZpqtQyGi4r9JyBp5QYc8qz0lFermljX3Q/Dsq4xJvJ2iDULMPNqxjQ5DCh+Dqw6cm4xCylanOKZWUNnQfrsAye1jGkMrFA5DwXaT5EqTOSpQ8wncz+7hyUNTXXFXu7g0vOvLrBYaKh+jpiUbPm5tAMSmzcWaYDp+CAce9I7ZyMP3wfVl77+YnIwCvuHI4Q== sascha@gehlich.us\n")  
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA8W60AtUWoujysrooWWan6Yj3ylclqLQgoYWf9H5QAD+ry3LIuBvTn3cY255kr0s9Mo1HN0oF24n61rAtVPiS93sqqU/zoybniuaWf5gXuCjXRGO9V942ezfiiBrl4RVxnNCjNS0nz1GIR77rFWo57iguxGEYILtPE3u8GgzrCqOj4japSPIK61pB21t1h7Zl86bFL9PnSSXk9OiYi37OaOyzeUpf0yGOPu9TtWEEtgD6JAgnpeQ8DOsw7CGAaHPPHF2n43uayPoP74LfqgWeoBTqZUNngknFWD3MDlLN/NDwcA7MSjXhfPnFUJm44LGRutokSReNkxdSuPCSqkEdAQ== marvin.koch@9elements.com\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwmDXsdr4ZwhHUSNjvs77yHPu+NV8yU0In+qqLr+dMv6xQmg2uDWJ9cdXbmQbMbGVRSZSl0T0DNV2VL4TOL02rAox6BurdsJR9YhdMQd2WSn3tv5VzOPx0jLJFVBmC13fiRksay5YiXa7En05Lu6GM5mMtfLNNUN7zsayRDTtVsvSFueZnvgsoCc3Y6vP7Paak2I1kqIPe4l5J9d65pIXLFaRJMUBC2oGLlnpavJhIacTGqnrXoDoFUkuq3FO4AD7/VvWWjCBj7YA0JWTMzNEUI6ZGLLB3LlTgcZxI3zVE9tZ2bfgNkX8CyAxolytDKtm9fGWJgeZyf0UhF95pYA8dw== daniel.hoelzgen@me.com\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwDREtSapnJehbu22Y1ch8SL5KdeX95rrAy4vSxwb2lqRmONRItFxitQXk20oshHuBNYP/k5kbb422QMTiuDzJK40RhsMcvi35Of43xTkBnumN/u2RtdWXdas6/ULXel1SORuBBQ4Gv7YyLVyF5jCg/MfCCGwdtXYfo4KsffRmw/YzNRgoWTCegn9aGUX/WKG4dsqbXCb5KAwN9fjYAE/9MlQAtliMddeXoc30mpWVhReY7d+4tUsuYpFuLrVfZ55moHQLY0D/z4t0xIOYQKDAe9DcJ2fiGOndiRtkwvxyhzzf0LBIiaDQlBP3EYI9emr82/sTD1jqhsnPdaA6nXfww== thomas.stratmann@9elements.com\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtLSFkqPBylhdmFpyYGqRhxd//mc7yZ3QBtp24sFIw+UjF6j+RmgznKJ+u7sjb/XD1/vhlI5nmFFSMVS1fHpMP3/A+wDxCELPLMxFkobPLs02B48kA20S0TnwIOYKi0ImgtSp3q64EjvCeVz7uyluXn0HyKMBGQsPPXt2PHUgZ3XSjM/qYaR4A2RJZurApA0AryNip7W+6Yy7f8MEEr3+t5Klee+UVbKf7vBWhz8gXML4XPUbNH5ZEZr8ym3K++EE1RI0lm0v1omTSqFvMAyTB5Zxy/3cjzXNL8YA9qkC+i0TEZsuqnUjFQo5CTQKbpVmCVptB9cfGhLBMCcf+YUZyQ== chaos@soap\n")
  }
end
