dep 'ssh' do
  requires [
    'openssh-server.bin',
    'secure-sshd-password-authentication',
    'secure-ssh-port',
    'ssh.authorized-keys'
  ]
  
  before {
    '/etc/ssh/sshd_config'.p.copy('/etc/ssh/sshd_config.backup')
  }
  
  after { 
    shell '/etc/init.d/ssh restart' 
  }
end

dep 'openssh-server.bin' do
  provides 'sshd'
end

dep 'secure-sshd-password-authentication' do
  met? {
    !'/etc/ssh/sshd_config'.p.read.match(/#PasswordAuthentication yes/)
  }
  
  meet {
    shell "sed -i -e 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config"    
  }
end

dep 'secure-ssh-port' do
  met? {
    !'/etc/ssh/sshd_config'.p.read.match(/Port 22/)
  }
  
  meet {
    shell "sed -i -e 's/^Port 22/Port 23222/' /etc/ssh/sshd_config"
  }
end

dep 'ssh.authorized-keys' do
  met? {
    if "/root/.ssh/authorized_keys".p.grep(/# generated by Babushka/)
      true
    else
      false
    end
  }
  
  meet {
    '/root/.ssh/authorized_keys'.p.append("# generated by Babushka\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzozCvmikj7094V99QonFrDMMGHWVqmpE6rXGq/DP7DTqyGxWQHiebS5iEKDNmnsBEbDSomV62ckXVwQQYh9dCXUOEOdk5fFeEel+jiqqllYkigb4lwlNiG7tmpH7xdewJ3w4qKowrLuuD6Voa1s4k4TsLp1G1YpQVFPdDfoyUjNCozKciW4DD4YXO4yIz8lfsAK6rVg63+Gbl8wTEQeLFzTtqBEpxXHWuadI8d1clUM2b/pNkK99MjIVLwCzUxSbtao1Lj0faRYjLpvBWu5GY6to6VIEV69s4+1pNe49hXuGxe0zUTxvjxWfQJRSIMRYrSXCtLXKOWuiJM1X/QucKQ== sebastiandeutsch\n")
    '/root/.ssh/authorized_keys'.p.append("ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Cet5vK+acVgrNSVrJJpaCMhlyUBwKDjpKDT9GVLp3J10Hizu0f/iEqaIJJRVZLslrMHFMOsZzssowFl17VQzTwocd/qAUP8g3y3dLP9XD6oJNmB7z/ABvgoYv0GRV5mzLurf8f6pThbopyIuMgSzHgkZpqtQyGi4r9JyBp5QYc8qz0lFermljX3Q/Dsq4xJvJ2iDULMPNqxjQ5DCh+Dqw6cm4xCylanOKZWUNnQfrsAye1jGkMrFA5DwXaT5EqTOSpQ8wncz+7hyUNTXXFXu7g0vOvLrBYaKh+jpiUbPm5tAMSmzcWaYDp+CAce9I7ZyMP3wfVl77+YnIwCvuHI4Q== sascha@gehlich.us\n")  
  }
end
